package com.camilolopes.readerweb.model.bean;

// default package
// Generated 03/03/2013 11:57:14 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Type generated by hbm2java
 */
@Entity
@Table(name = "type", catalog = "reader")
public class Type implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1149738706302244212L;
	private TypeId id;
	private User user;
	private String description;

	public Type() {
	}

	public Type(TypeId id, User user) {
		this.id = id;
		this.user = user;
	}

	public Type(TypeId id, User user, String description) {
		this.id = id;
		this.user = user;
		this.description = description;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false)),
			@AttributeOverride(name = "userId", column = @Column(name = "USER_id", nullable = false)) })
	public TypeId getId() {
		return this.id;
	}

	public void setId(TypeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_id", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "DESCRIPTION", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
