package com.camilolopes.readerweb.model.bean;

// default package
// Generated 03/03/2013 11:57:14 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TypeId generated by hbm2java
 */
@Embeddable
public class TypeId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 689485316652147140L;
	private int id;
	private int userId;

	public TypeId() {
	}

	public TypeId(int id, int userId) {
		this.id = id;
		this.userId = userId;
	}

	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "USER_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TypeId))
			return false;
		TypeId castOther = (TypeId) other;

		return (this.getId() == castOther.getId())
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
